### ISSUE TITLE
Latest version is not compatible with Xcode 11 Swift 5.1

### ISSUE THREAD

**Issue by vishalvirodhia** [Vadim-Yelagin/DataSource#22]
<img width="620" alt="DataSource" src="https://user-images.githubusercontent.com/10043749/65853606-b479b800-e377-11e9-8dcc-f4da5677e94b.png">

**Comment by DheerajDhamija14** [comment]
<img width="583" alt="Screenshot 2019-12-06 at 11 01 28 AM" src="https://user-images.githubusercontent.com/37287616/70298568-14795880-1818-11ea-8895-4564ac8f3862.png">

Trying to update to latest version gives this error.
